<%@ Page Language="C#" MasterPageFile="~/Views/MasterPage.Master" AutoEventWireup="true" CodeBehind="frmChat.aspx.cs" Inherits="ConalWeb.Views.frmChat" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <!-- estilos específicos del view -->
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
 
    <div style="width: 450px; margin-left: 190px; margin-right: 190px">

        <div style="text-align:center" class="header bg-blue">Chat</div>
        <div class="body bg-gray">

            Total Users Online:<div id="count"></div>
            <br />
            <asp:Label ID="Label_nombreCuenta" runat="server" Text="Deberia mostrar el nombre cuenta"></asp:Label>
                
            <input type="text" id="name" name="name" runat="server" />
            <br />
            <asp:Label ID="Label_comunidad" runat="server" Text="Deberia mostrar el nombre comunidad"></asp:Label>
            <input type="text" id="g" name="g" runat="server" />
               
            <br />
            <div class="panel panel-default" style="height:40px; width:100%; margin-top:10px;">
                <div class="panel-body">
                    <ul id="listOfMessage">
                            
                    </ul>
                </div>
            </div>
            <br />
            <textarea id="message" class="form-control" style="height:25px; width:100%" name="message"></textarea>
        </div>
        <div class="footer bg-gray">
            <input type="button" id="send" value="Send" class="btn btn-success"  />
        </div>
    </div>

<!--Script references. -->
<!--Reference the jQuery library. -->
<script src="Scripts/jquery-3.3.1.min.js" "></script>
<!--Reference the SignalR library. -->
<script src="/Scripts/jquery.signalR-2.3.0.js"></script>
<!--Reference the autogenerated SignalR hub script. -->
<script src="/signalr/hubs"></script>
<!--Add script to update the page and send messages.-->
<script type="text/javascript">
    $(function () {

        var chat = $.connection.myHub; // Se cae aqui

        chat.client.receive = function (name, conId, msge) {
       
            $('#listOfMessage').append("<li>" + name + "(Connection ID=" + conId + ")" + "Says" + " : " + msge + "</li>");
        }
        var n = $('#name').val();
        var g = $('#g').val();
        alert("funcioná care picha");

        chat.client.countno = function (count) {

            $('#count').text(count);
        }
        chat.connection.start().done(function () {
            chat.server.join(g);
            $('#send').click(function () {
                alert("funcioná care picha");
                chat.server.sendMessage($('#name').val(), $('#message').val(), g);
            });
        });
        chat.client.sayClient = function (reply) {
            $('#admin').html(reply);
        }
    });
</script>
</asp:Content>
