<%@ Page Language="C#"AutoEventWireup="true" CodeBehind="frmChat.aspx.cs" Inherits="ConalWeb.Views.frmChat" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        #cajaMensajes {
            width: 549px;
            height: 143px;
        }
        #TextArea1 {
            height: 260px;
            width: 580px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div class="container" style="align-content:center">
        <input type="text" id="miMensaje" />
        <input type="button" id="btnEnviarMsg" value="Send" />
        <input type="hidden" id="nombreUsuario" runat="server" />
        <input type="hidden" id="nombreComunidad" runat="server" />
        <ul id="cajaMensajes"></ul>
    </div>
    
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.3.1.min.js" "></script>
    <!--Reference the SignalR library. -->
    <script src="/Scripts/jquery.signalR-2.3.0.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">

        // TODO: Lo de "chat.server" son los metodos de ChatHub.cs, "chat.client" ya es otra cosa de jquery

        $(function () {
            // Declare a proxy to reference the hub.
            var chat = $.connection.chatHub;
            // Create a function that the hub can call to broadcast messages.

            //var nombreComunidad = "Comunidad 1";

            chat.client.receive = function (name, conId, msge) {
                $('#cajaMensajes').append("<li>" + name + " : " + msge + "</li>");
            }

            /*chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message.
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page.
                $('#cajaMensajes').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };*/
            // Get the user name and store it to prepend to messages.
            //$('#nombreUsuario').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            $('#miMensaje').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {

                // unirse al grupo
                chat.server.join($('#nombreComunidad').val());

                $('#btnEnviarMsg').click(function () {
                    // Call the Send method on the hub.
                    //chat.server.send($('#nombreUsuario').val(), $('#message').val());
                    chat.server.sendMessage($('#nombreUsuario').val(), $('#miMensaje').val(), $('#nombreComunidad').val());
                    // Clear text box and reset focus for next comment.
                    $('#miMensaje').val('').focus();
                });

                $("#miMensaje").keypress(function (e) {
                if (e.which == 13) {
                    $('#btnEnviarMsg').click();
                }
            });
            });
        });
    </script>
        <textarea id="TextArea_mensajes" runat="server"></textarea>
    </form>
</body>
</html>
